Repository McNamara84/ladis, pull requests merged in 2025-08, with the labels that each got.

#215 chore/add wiki to .gitignore
  .gitignore
Labels: enhancement

#213 Feature: Table and input form for persons
  README.md
  app/Http/Controllers/InputFormPersonController.php
  app/Http/Controllers/PersonController.php
  resources/views/inputform_person.blade.php
  resources/views/layouts/app.blade.php
  resources/views/persons/index.blade.php
  routes/web.php
  tests/Feature/InputFormPersonControllerTest.php
  tests/Feature/PersonListTest.php
Labels: documentation, enhancement

#216 Fix: Form element text overflow and inline CSS
  public/css/error.css
  resources/sass/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/419.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/502.blade.php
  resources/views/inputform_process.blade.php
Labels: bug

#227 Feature: Collapsible search filter
  resources/js/searchFilters.js
  resources/sass/_filters.scss
  resources/views/partials/_svg-sprite.blade.php
  resources/views/search/index.blade.php
  tests/Feature/SearchFilterCollapseTest.php
Labels: enhancement

#226 Feature/Normalized updated_at handling for pages
  .env.example
  app/Http/Controllers/LegalNoticeController.php
  app/Http/Controllers/PrivacyPolicyController.php
  app/Support/helpers.php
  composer.json
  config/site.php
  resources/views/layouts/app.blade.php
  resources/views/legal_notice.blade.php
  tests/Feature/LegalNoticePageTest.php
  tests/Feature/PrivacyPolicyPageTest.php
  tests/Unit/Support/HelpersTest.php
Labels: bug, enhancement

#232 Fix: Add institution selection to device input form
  app/Http/Controllers/InputFormDeviceController.php
  resources/views/inputform_device.blade.php
  tests/Feature/DeviceFormTest.php
  tests/Feature/DeviceTest.php
Labels: bug

#233 Chore: Dependencies update
  composer.lock
  package-lock.json
Labels: enhancement

#235 Feature: Add Venues management
  README.md
  app/Http/Controllers/VenueController.php
  database/factories/VenueFactory.php
  resources/views/inputform_venue.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/_svg-sprite.blade.php
  resources/views/venues/index.blade.php
  routes/web.php
  tests/Feature/VenueCreateTest.php
  tests/Feature/VenueListTest.php
Labels: documentation, enhancement

#236 Feature: Artifacts management
  README.md
  app/Http/Controllers/ArtifactController.php
  app/Http/Controllers/ArtifactInputController.php
  resources/views/artifacts/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/_svg-sprite.blade.php
  routes/web.php
  tests/Feature/ArtifactInputControllerTest.php
  tests/Feature/ArtifactListTest.php
Labels: enhancement

#238 Feature: Delete modal as blade component
  resources/views/artifacts/index.blade.php
  resources/views/components/delete-modal.blade.php
  resources/views/devices/index.blade.php
  resources/views/institutions/index.blade.php
  resources/views/materials/index.blade.php
  resources/views/persons/index.blade.php
  resources/views/processes/index.blade.php
  resources/views/projects/index.blade.php
  resources/views/user_management.blade.php
  resources/views/venues/index.blade.php
Labels: enhancement
