Repository McNamara84/ladis, pull requests merged in 2025-07, with the labels that each got.

#170 Feature/device seeder test, user seeder test, institution seeder test
  README.md
  tests/Feature/DeviceSeederTest.php
  tests/Feature/InstitutionSeederTest.php
  tests/Feature/UserSeederTest.php
Labels: enhancement

#171 Documentation: Add License for Code
  LICENSE
  README.md
Labels: documentation

#162 Feature: Navigation Overhaul
  LICENSE
  README.md
  app/Http/Controllers/DeviceInputController.php
  app/Providers/ViewServiceProvider.php
  app/View/Components/Icon.php
  app/View/Components/Link.php
  app/View/Components/Nav/Divider.php
  app/View/Components/Nav/Item.php
  resources/sass/_colors.scss
  resources/sass/app.scss
  resources/views/components/link.blade.php
  resources/views/components/nav/item.blade.php
  resources/views/inputform_device.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/_svg-sprite.blade.php
  routes/web.php
  tests/Feature/DeviceInputControllerTest.php
  tests/Feature/DeviceInputFormRouteTest.php
  tests/Feature/DeviceInputFormTest.php
  tests/Feature/InputFormInstitutionTest.php
  tests/Feature/MaterialInputFormRouteTest.php
  tests/Feature/MaterialInputFormValidationTest.php
  tests/Unit/View/Components/IconTest.php
  tests/Unit/View/Components/LinkTest.php
Labels: bug, enhancement, Lab Tutorial

#177 Feature: New site with table of all devices
  LICENSE
  README.md
  app/Http/Controllers/DeviceController.php
  app/Http/Controllers/InputFormDeviceController.php
  resources/views/devices/index.blade.php
  routes/web.php
  tests/Feature/DeviceFormTest.php
  tests/Feature/DeviceListTest.php
  tests/Feature/DeviceSeederTest.php
  tests/Feature/InputFormDeviceControllerTest.php
  tests/Feature/InstitutionSeederTest.php
  tests/Feature/UserSeederTest.php
Labels: enhancement

#182 Feature: New sites with table of all institutions
  README.md
  app/Http/Controllers/InstitutionController.php
  resources/views/institutions/index.blade.php
  routes/web.php
  tests/Feature/InputFormInstitutionTest.php
  tests/Feature/InstitutionListTest.php
Labels: enhancement

#188 Hotfix: Cleaning up routes
  routes/web.php
Labels: bug

#186 Chore: Update name in package-lock
  package-lock.json
Labels: enhancement

#174 Eingabeformular für artifacts (DE: (Behandlungs-)Objekte)
  app/Http/Controllers/ArtifactInputController.php
  app/Models/Artifact.php
  resources/views/inputform_artifact.blade.php
  routes/web.php
  tests/Feature/ArtifactInputControllerTest.php
  tests/Feature/ArtifactInputRouteTest.php
Labels: enhancement

#192 feature/explain ladis acronym
  app/Providers/ViewServiceProvider.php
  config/app.php
  resources/views/welcome.blade.php
Labels: enhancement

#179 Fix: Saving new projects via input form
  app/Http/Controllers/ProjectInputController.php
  app/Models/Project.php
  public/images/ladis-illustration-01-1000w.webp
  public/images/ladis-illustration-01-1200w.webp
  public/images/ladis-illustration-01-1600w.webp
  public/images/ladis-illustration-01-2000w.webp
  public/images/ladis-illustration-01-400w.webp
  public/images/ladis-illustration-01-600w.webp
  public/images/ladis-illustration-01-800w.webp
  resources/views/inputform_project.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: bug

#168 Feature: Extend Advanced Search with search option for year and cooling
  README.md
  app/Http/Controllers/SearchController.php
  resources/js/searchFilters.js
  resources/views/search/_filters.blade.php
  tests/Feature/SearchControllerTest.php
Labels: documentation, enhancement

#193 Fix. Main menu links not working
  resources/views/devices/index.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: bug

#199 Testing: Missing factories added
  README.md
  app/Models/Image.php
  app/Models/Project.php
  database/factories/ConditionFactory.php
  database/factories/ConfigurationFactory.php
  database/factories/DamagePatternFactory.php
  database/factories/ImageFactory.php
  database/factories/MaterialFactory.php
  database/factories/PartialSurfaceFactory.php
  database/factories/ProcessFactory.php
  database/factories/ProjectFactory.php
  database/factories/SampleSurfaceFactory.php
  tests/Feature/ArtifactFactoryTest.php
  tests/Feature/ArtifactInputControllerTest.php
  tests/Feature/CityFactoryTest.php
  tests/Feature/ConditionFactoryTest.php
  tests/Feature/ConditionTest.php
  tests/Feature/ConfigurationFactoryTest.php
  tests/Feature/DamagePatternFactoryTest.php
  tests/Feature/DamagePatternTest.php
  tests/Feature/DeviceFactoryTest.php
  tests/Feature/DeviceTest.php
  tests/Feature/FederalStateFactoryTest.php
  tests/Feature/ImageFactoryTest.php
  tests/Feature/ImageTest.php
  tests/Feature/LocationFactoryTest.php
  tests/Feature/PartialSurfaceFactoryTest.php
  tests/Feature/PartialSurfaceTest.php
  tests/Feature/ProcessFactoryTest.php
  tests/Feature/ProcessInputControllerTest.php
  tests/Feature/ProcessTest.php
  tests/Feature/ProjectFactoryTest.php
  tests/Feature/ProjectTest.php
  tests/Feature/SampleSurfaceFactoryTest.php
  tests/Feature/SampleSurfaceTest.php
  tests/Feature/UserFactoryTest.php
  tests/Feature/VenueFactoryTest.php
  tests/Feature/VenueTest.php
Labels: enhancement

#208 Feature: Laravel log file rotation
  .env.example
  README.md
Labels: documentation, enhancement

#211 Feature: Table for projects
  README.md
  app/Http/Controllers/ProjectController.php
  resources/views/layouts/app.blade.php
  resources/views/projects/index.blade.php
  routes/web.php
  tests/Feature/ProjectListTest.php
Labels: enhancement
